<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BalajiTrader.Business\BalajiTrader.Business.csproj" />
    <ProjectReference Include="..\BalajiTrader.DataAccess\BalajiTrader.DataAccess.csproj" />
    <ProjectReference Include="..\BalajiTrader.Data\BalajiTrader.Data.csproj" />
  </ItemGroup>

</Project>
